version: "3.8"

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-shoppinglist-db-pw
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
#   minio:
#     image: minio/minio
#     ports:
#       - "9000:9000"
#       - "9001:9001"
#     volumes:
#       - minio_storage:/data
#     environment:
#       MINIO_ROOT_USER: admin
#       MINIO_ROOT_PASSWORD: Strong#Pass#2023
#     command: server --console-address ":9001" /data

#   backendend:
#     container_name: shopping-backend
#     build:
#       context: ./
#       target: production
#     image: shopping-backend
#     depends_on:
#       - db
#     ports:
#       - 3001:3001
#     environment:
#       NODE_ENV: production
#       DB_HOST: db
#       DB_PORT: 3306
#       DB_USER: root
#       DB_PASSWORD: root_password
#       DB_NAME: shoppingdb
#     links:
#       - db

#   frontend:
#     container_name: shopping-frontend
#     build:
#       context: ./
#       target: production
#     image: shopping-frontend
#     depends_on:
#       - db
#     ports:
#       - 3000:3000
#     environment:
#       NODE_ENV: production
#       DB_HOST: db
#       DB_PORT: 3306
#       DB_USER: root
#       DB_PASSWORD: root_password
#       DB_NAME: shoppingdb
#     links:
#       - db

volumes:
  db:
    driver: local
  # minio_storage: {}
